#!/bin/bash

WORKDIR="${WORKDIR:-/opt/letsencrypt}"
cd $WORKDIR || { echo "Missing program directory" ; exit 1 ; }

[[ ! -t 0 ]] && {
   exec >> >(tee -a letsencrypt-cron.log)
   exec 2>&1
}

[[ ! -r le.config ]] && {
    echo "FATAL: Missing le.config"
    exit 1
}

if [[ ! -x ./dehydrated ]] ; then
    curl -sL https://raw.githubusercontent.com/lukas2511/dehydrated/3d97799d6a269a727fb041f60e0b587c273fbe95/dehydrated -o dehydrated
    chmod +x dehydrated
    if [[ ! -x ./dehydrated ]] ; then
        echo "FATAL: Failed to download and chmod dehydrated :("
        exit 1
    fi
    ./dehydrated --register --accept-terms
fi

if [[ ! -x ./le-dns.sh ]] ; then
    echo "FATAL: missing le-dns.sh (or not executable)"
    exit 1
fi

function backup_file() {
    if [[ -r "$1" ]] ; then
        mv "$1" "${1}.backup-$(date +%Y-%m-%d_%H-%M-%S)"
        return $?
    fi
}

function renew() {
    if ! ./dehydrated --cron --domain "$1" --hook ./le-dns.sh --challenge dns-01 ; then
      echo "ERROR: renew of $1 failed!"
      return 1
    fi

    return 0
}

function install_new() {
    priv_key_dest=$(grep -- "domain=\"$1\"" le.config | grep -Po '\bpriv_key_dest="\K[^"]+(?=")')
    cert_dest=$(grep -- "domain=\"$1\"" le.config | grep -Po '\bcert_dest="\K[^"]+(?=")')
    chain_dest=$(grep -- "domain=\"$1\"" le.config | grep -Po '\bchain_dest="\K[^"]+(?=")')
    fullchain_dest=$(grep -- "domain=\"$1\"" le.config | grep -Po '\bfullchain_dest="\K[^"]+(?=")')

    if [[ "$priv_key_dest" != "" ]] ; then
        backup_file "$priv_key_dest"
        cp "certs/$1/privkey.pem" "$priv_key_dest"
    fi

    if [[ "$cert_dest" != "" ]] ; then
        backup_file "$cert_dest"
        cp "certs/$1/cert.pem" "$cert_dest"
    fi

    if [[ "$chain_dest" != "" ]] ; then
        backup_file "$chain_dest"
        cp "certs/$1/chain.pem" "$chain_dest"
    fi

    if [[ "$fullchain_dest" != "" ]] ; then
        backup_file "$fullchain_dest"
        cp "certs/$1/fullchain.pem" "$fullchain_dest"
    fi

    exec_after=$(grep -- "domain=\"$1\"" le.config | grep -Po '\bexec_after="\K[^"]+(?=")')
    if [[ "$exec_after" != "" ]] ; then
        echo "Executing: $exec_after"
        bash -c "$exec_after"
    fi
}

domains=$(grep -Po '^[^#]*domain=.*$' le.config | grep -Po '\bdomain="\K[^"]+(?=")')

for i in $domains ; do
    if [[ -r certs/$i/cert.pem ]] ; then
        # if less than 10 days remain, renew
        if ! openssl x509 -in "certs/$i/cert.pem" -checkend 864000 -noout ; then
           renew "$i" && install_new "$i"
        fi
    else
        renew "$i" && install_new "$i"
    fi

done
